import React from 'react'
import styles from '../styles/styles.module.css'
import Head from 'next/head'
import Navigation from './Navigation/Navigation';

type Props = {
    children: React.ReactNode;
}

const Layout = ({children}: Props) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Navigation/>
        {children}

      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Layout